from rest_framework.routers import DefaultRouter
from .views import ApplicationViewSet
from django.urls import path, include

router = DefaultRouter()
router.register(r"applications", ApplicationViewSet, basename="application")


urlpatterns = [
    # Include the URLs generated by the router
    # This line creates the 'application-list', 'application-detail', etc. names
    path('', include(router.urls)),
]