# Generated by Django 5.2.6 on 2025-09-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('employer', 'Employer'), ('applicant', 'Applicant'), ('admin', 'Admin')], default='employer', max_length=10),
        ),
    ]
